FROM eclipse-temurin:21-jdk-jammy

WORKDIR /app

RUN apt-get update && apt-get install -y curl && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && apt-get install -y nodejs && rm -rf /var/lib/apt/lists/*

COPY backend ./backend
COPY java ./java

RUN java -version
RUN javac -version

WORKDIR /app/backend
RUN npm install

WORKDIR /app/java
RUN javac SmartRequestPrioritizer.java

RUN java -cp /app/java SmartRequestPrioritizer TRANSCRIPT 4 7 emergency

WORKDIR /app/backend

ENV NODE_ENV=production
ENV PORT=80

EXPOSE 80

CMD ["node", "server.js"]
